version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/client'
