services:
  db:
    image: mysql:8.0
    ports:
      - '13306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: playground
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
