services:
  app:
    image: node:22-bookworm
    working_dir: /app
    command: ['npm', 'run', 'start:debug']
    ports:
      - '13000:3000'
    environment:
      DATABASE_URL: 'mysql://user:password@db:3306/playground'
    volumes:
      - .:/app
  db:
    image: mysql:8.0
    ports:
      - '13306:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: playground
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d

volumes:
  db-data:
