name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        tests: ['test:e2e'] # TODO Add more tests
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: playground
        ports:
          - '13306:3306'
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: mysql://root:@localhost:13306/playground
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Prisma deploy
        run: npx prisma migrate deploy
      - name: Run tests
        run: npm run ${{ matrix.tests }}
      - uses: ArtiomTr/jest-coverage-report-action@v2
