name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    permissions:
      checks: write
      pull-requests: write
    strategy:
      matrix:
        test-scripts:
          - 'test'
          - 'test:e2e'
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: playground
        ports:
          - '13306:3306'
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: mysql://root:@localhost:13306/playground
      COVERAGE_REPORT_DIR: ${{ github.workspace }}/coverage
    steps:
      - uses: actions/cache/restore@v4
        id: restore-cache
        with:
          key: ${{ matrix.test-scripts }}-coverage-report
          path: env.COVERAGE_REPORT_DIR

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Prisma deploy
        run: npx prisma migrate deploy

      - name: Run tests
        run: npm run ${{ matrix.test-scripts }} -- --ci --json --coverage --testLocationInResults --outputFile=report.json

      - name: Set base coverage file if cache not found
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: cp report.json ${{ env.COVERAGE_REPORT_DIR }} && ls -la ${{ env.COVERAGE_REPORT_DIR }}

      - uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event_name == 'pull_request'
        with:
          skip-step: all
          custom-title: Coverage Report (${{ matrix.test-scripts }})
          coverage-file: report.json
          base-coverage-file: ${{ env.COVERAGE_REPORT_DIR }}/report.json

      - name: Move coverage report for cache
        #if: github.ref == 'refs/heads/main'
        if: github.event_name == 'pull_request'
        run: mv report.json ${{ env.COVERAGE_REPORT_DIR }}

      - uses: actions/cache/save@v4
        #if: github.ref == 'refs/heads/main'
        if: github.event_name == 'pull_request'
        with:
          key: ${{ matrix.test-scripts }}-coverage-report
          path: ${{ env.COVERAGE_REPORT_DIR }}
